import { z } from 'zod'

import { authRequirementSchema } from './base'

export const coverageSchema = z.enum(['global', 'conus', 'regional', 'local'])
export const sourceStatusSchema = z.enum(['implemented', 'scaffolded'])
export const sourceOfficialitySchema = z.enum(['official', 'secondary'])

export const weatherSourceCatalogEntrySchema = z.object({
  sourceId: z.string(),
  productId: z.string(),
  family: z.string(),
  label: z.string(),
  officiality: sourceOfficialitySchema,
  status: sourceStatusSchema.default('implemented'),
  authRequirement: authRequirementSchema,
  geographicCoverage: coverageSchema,
  temporalCoverage: z.string(),
  updateCadence: z.string(),
  validTimeSemantics: z.string(),
  supportedFormats: z.array(z.string()),
  unitsOrProjectionNotes: z.string(),
  latencyOrCostNotes: z.string(),
  recommendedUseCases: z.array(z.string()),
  implemented: z.boolean().default(true),
})

export type WeatherSourceCatalogEntry = z.infer<
  typeof weatherSourceCatalogEntrySchema
>
export type WeatherSourceCatalogInput = z.input<
  typeof weatherSourceCatalogEntrySchema
>

const weatherSourceCatalogInput = [
  {
    sourceId: 'us-census-geocoder',
    productId: 'address-normalization',
    family: 'location',
    label: 'U.S. Census Geocoder',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'current',
    updateCadence: 'on demand',
    validTimeSemantics: 'geographic normalization only',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'lat/lon WGS84 output',
    latencyOrCostNotes: 'free public API',
    recommendedUseCases: [
      'U.S. address-like place normalization',
      'reverse geocoding support',
    ],
  },
  {
    sourceId: 'geonames',
    productId: 'global-geocoder',
    family: 'location',
    label: 'GeoNames',
    officiality: 'secondary',
    status: 'scaffolded',
    authRequirement: 'optional',
    geographicCoverage: 'global',
    temporalCoverage: 'current',
    updateCadence: 'on demand',
    validTimeSemantics: 'geographic normalization only',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'lat/lon WGS84 output',
    latencyOrCostNotes: 'free tier with username',
    recommendedUseCases: ['global place fallback'],
  },
  {
    sourceId: 'open-meteo-geocoding',
    productId: 'global-place-search',
    family: 'location',
    label: 'Open-Meteo Geocoding API',
    officiality: 'secondary',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'current',
    updateCadence: 'on demand',
    validTimeSemantics: 'geographic normalization only',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'lat/lon WGS84 output with ranked place results',
    latencyOrCostNotes: 'free public API for lightweight geocoding fallback',
    recommendedUseCases: ['city and region fallback', 'postcode fallback'],
  },
  {
    sourceId: 'weather-gov',
    productId: 'points-forecast-hourly-observations-alerts',
    family: 'official-forecast',
    label: 'NWS Weather.gov API',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'current through 7 days',
    updateCadence: 'minutes to hours depending on product',
    validTimeSemantics: 'official valid periods from NWS products',
    supportedFormats: ['json', 'geojson'],
    unitsOrProjectionNotes: 'native imperial from NWS, normalized on read',
    latencyOrCostNotes: 'free public API',
    recommendedUseCases: [
      'current conditions',
      'forecast',
      'alerts',
      'official weather answers',
    ],
  },
  {
    sourceId: 'aviationweather-gov',
    productId: 'metar-taf',
    family: 'aviation',
    label: 'Aviation Weather Center Data API',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'current through 30 hours',
    updateCadence: 'minutes',
    validTimeSemantics: 'observation or forecast valid times from product',
    supportedFormats: ['json', 'xml'],
    unitsOrProjectionNotes: 'aviation native units',
    latencyOrCostNotes: 'free public API',
    recommendedUseCases: ['METAR', 'TAF', 'flight-weather context'],
  },
  {
    sourceId: 'spc',
    productId: 'convective-outlook-page',
    family: 'severe',
    label: 'Storm Prediction Center Outlook Page',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'broad severe-weather outlook windows',
    updateCadence: 'scheduled outlook updates',
    validTimeSemantics: 'headline page issue timing',
    supportedFormats: ['html', 'text'],
    unitsOrProjectionNotes: 'headline and text context only in the current MVP',
    latencyOrCostNotes:
      'free public page fetch; structured SPC product parsing remains planned',
    recommendedUseCases: [
      'severe-weather setup',
      'broader severe-weather context',
    ],
  },
  {
    sourceId: 'spc-fire',
    productId: 'fire-weather-outlooks',
    family: 'fire-weather',
    label: 'SPC Fire Weather Outlooks',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'day 1 through day 8 fire-weather outlook windows',
    updateCadence: 'scheduled outlook updates',
    validTimeSemantics: 'headline page issue timing',
    supportedFormats: ['html', 'text'],
    unitsOrProjectionNotes: 'headline and text context only until structured parsing is wired',
    latencyOrCostNotes: 'free public page fetch',
    recommendedUseCases: ['fire-weather setup', 'wildfire spread-risk context'],
  },
  {
    sourceId: 'wpc',
    productId: 'qpf-ero',
    family: 'precipitation',
    label: 'Weather Prediction Center',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'hours to day 7',
    updateCadence: 'scheduled forecast cycles',
    validTimeSemantics: 'issue and forecast valid periods',
    supportedFormats: ['json', 'text', 'image'],
    unitsOrProjectionNotes: 'QPF inches, outlook categorical',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'rainfall context',
      'flood potential',
      'multi-day precipitation questions',
    ],
  },
  {
    sourceId: 'wpc-winter',
    productId: 'winter-weather-probabilities',
    family: 'winter-weather',
    label: 'WPC Winter Weather Desk',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'day 1 through day 3 winter-weather probabilities',
    updateCadence: 'scheduled forecast cycles',
    validTimeSemantics: 'issue and forecast valid periods',
    supportedFormats: ['html', 'text', 'image'],
    unitsOrProjectionNotes: 'probabilistic snowfall and freezing-rain context',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'snow and ice questions',
      'winter storm timing',
      'freezing-rain risk',
    ],
  },
  {
    sourceId: 'wpc-medium',
    productId: 'medium-range-hazards',
    family: 'medium-range',
    label: 'WPC Medium Range Hazards',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'day 3 through day 7 hazards and setup',
    updateCadence: 'scheduled forecast cycles',
    validTimeSemantics: 'issue and forecast valid periods',
    supportedFormats: ['html', 'text', 'image'],
    unitsOrProjectionNotes: 'hazards, heights, surface systems, and key messages',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'synoptic setup',
      'medium-range hazards',
      'impact-oriented weather briefings',
    ],
  },
  {
    sourceId: 'nwps',
    productId: 'stream-forecast-observations',
    family: 'hydrology',
    label: 'NWPS',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'regional',
    temporalCoverage: 'current through official river forecast horizons',
    updateCadence: 'minutes to hours',
    validTimeSemantics: 'gauge obs time and forecast valid time',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'river stage and flow metadata',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: ['river forecast context', 'flood-category summaries'],
  },
  {
    sourceId: 'nexrad',
    productId: 'base-reflectivity-velocity',
    family: 'radar',
    label: 'NEXRAD',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'regional',
    temporalCoverage: 'near real time',
    updateCadence: 'minutes',
    validTimeSemantics: 'scan time',
    supportedFormats: ['ar2v', 'png', 'json'],
    unitsOrProjectionNotes: 'radar polar grids',
    latencyOrCostNotes: 'public access with decoder requirements',
    recommendedUseCases: ['storm structure', 'short-fuse analysis'],
  },
  {
    sourceId: 'goes',
    productId: 'visible-ir-water-vapor',
    family: 'satellite',
    label: 'GOES',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'regional',
    temporalCoverage: 'near real time',
    updateCadence: 'minutes',
    validTimeSemantics: 'scan time',
    supportedFormats: ['netcdf', 'png'],
    unitsOrProjectionNotes: 'projection varies by product',
    latencyOrCostNotes: 'public access with image processing requirements',
    recommendedUseCases: [
      'cloud evolution',
      'water vapor analysis',
      'satellite interpretation',
    ],
  },
  {
    sourceId: 'nbm',
    productId: 'national-blend-of-models',
    family: 'blend',
    label: 'National Blend of Models',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'hours through day 7',
    updateCadence: 'scheduled blend cycles',
    validTimeSemantics: 'issue and forecast valid periods',
    supportedFormats: ['grib2', 'json'],
    unitsOrProjectionNotes: 'calibrated blend of multiple guidance sources',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'near-term calibration',
      'official blend context',
      'hourly forecast refinement',
    ],
  },
  {
    sourceId: 'rtma',
    productId: 'real-time-mesoscale-analysis',
    family: 'analysis',
    label: 'RTMA',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'near real time',
    updateCadence: 'hourly',
    validTimeSemantics: 'analysis valid time',
    supportedFormats: ['grib2', 'json'],
    unitsOrProjectionNotes: 'mesoscale analysis fields',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'what is happening now',
      'surface analysis calibration',
      'current-condition context',
    ],
  },
  {
    sourceId: 'urma',
    productId: 'unrestricted-mesoscale-analysis',
    family: 'analysis',
    label: 'URMA',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'near real time',
    updateCadence: 'hourly',
    validTimeSemantics: 'analysis valid time',
    supportedFormats: ['grib2', 'json'],
    unitsOrProjectionNotes: 'mesoscale analysis fields with broader coverage',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'surface analysis calibration',
      'current-condition context',
      'near-term blend checks',
    ],
  },
  {
    sourceId: 'mrms',
    productId: 'reflectivity-qpe',
    family: 'radar-analysis',
    label: 'MRMS',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'near real time',
    updateCadence: 'minutes',
    validTimeSemantics: 'analysis valid time',
    supportedFormats: ['grib2', 'png'],
    unitsOrProjectionNotes: 'gridded analysis products',
    latencyOrCostNotes: 'public data with decode cost',
    recommendedUseCases: [
      'precipitation totals',
      'composite reflectivity',
      'flood context',
    ],
  },
  {
    sourceId: 'rap',
    productId: 'rapid-refresh',
    family: 'model',
    label: 'RAP',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: '0 to 21 hours',
    updateCadence: 'hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: [
      'very short-range timing',
      'analysis and forecast handoff',
      'mesoscale evolution',
    ],
  },
  {
    sourceId: 'nam',
    productId: 'north-american-mesoscale',
    family: 'model',
    label: 'NAM',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: '0 to 84 hours',
    updateCadence: '6-hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: [
      'storm timing',
      'snow band placement',
      'mid-range mesoscale context',
    ],
  },
  {
    sourceId: 'href',
    productId: 'high-resolution-ensemble-forecast',
    family: 'model',
    label: 'HREF',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: '0 to 48 hours',
    updateCadence: 'hourly',
    validTimeSemantics: 'ensemble init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'high-resolution ensemble guidance',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: [
      'severe-convection confidence',
      'heavy-rain banding',
      'short-range spread checks',
    ],
  },
  {
    sourceId: 'hrrr',
    productId: 'short-range-model',
    family: 'model',
    label: 'HRRR',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: '0 to 48 hours',
    updateCadence: 'hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: [
      'storm timing',
      'ongoing convection',
      'short-range detail',
    ],
  },
  {
    sourceId: 'gfs',
    productId: 'global-forecast-system',
    family: 'model',
    label: 'GFS',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: '0 to 16 days',
    updateCadence: '6-hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: ['days 2-10 context', 'broad synoptic pattern'],
  },
  {
    sourceId: 'gefs',
    productId: 'global-ensemble-forecast-system',
    family: 'model',
    label: 'GEFS',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: '0 to 16 days',
    updateCadence: '6-hourly',
    validTimeSemantics: 'ensemble init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: ['spread and confidence', 'medium-range comparison'],
  },
  {
    sourceId: 'ecmwf-open-data',
    productId: 'ifs-aifs-open',
    family: 'model',
    label: 'ECMWF Open Data',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'optional',
    geographicCoverage: 'global',
    temporalCoverage: '0 to 15 days',
    updateCadence: '6-hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public subset, optional richer access with PAT',
    recommendedUseCases: ['medium-range comparison', 'global pattern context'],
  },
  {
    sourceId: 'nhc',
    productId: 'tropical-outlook-advisories',
    family: 'tropical',
    label: 'National Hurricane Center',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'current through active tropical cycles',
    updateCadence: 'scheduled advisory updates',
    validTimeSemantics: 'issue and advisory valid periods',
    supportedFormats: ['html', 'text', 'xml'],
    unitsOrProjectionNotes: 'public-facing advisory and outlook products',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'hurricane track context',
      'tropical outlooks',
      'watch and warning interpretation',
    ],
  },
  {
    sourceId: 'wavewatch3',
    productId: 'ncep-wavewatch-iii',
    family: 'marine',
    label: 'WAVEWATCH III',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'hours through medium range',
    updateCadence: 'scheduled forecast cycles',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'wave-height, swell, and period guidance',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'wave height',
      'swell period',
      'marine routing',
      'coastal hazard context',
    ],
  },
  {
    sourceId: 'rtofs',
    productId: 'real-time-ocean-forecast-system',
    family: 'marine',
    label: 'RTOFS',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'current through medium range',
    updateCadence: 'scheduled forecast cycles',
    validTimeSemantics: 'nowcast and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'ocean nowcast and forecast fields',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'sea-surface temperature',
      'ocean current context',
      'marine routing',
    ],
  },
  {
    sourceId: 'upper-air',
    productId: 'sounding-archive',
    family: 'upper-air',
    label: 'Upper-Air Soundings',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'current and archived soundings',
    updateCadence: 'twice daily and on demand',
    validTimeSemantics: 'observation launch and archive times',
    supportedFormats: ['html', 'text', 'json'],
    unitsOrProjectionNotes: 'sounding, skew-T, and hodograph context',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'CAPE and shear analysis',
      'severe-weather setup',
      'teaching and research',
    ],
  },
  {
    sourceId: 'ncei-cdo',
    productId: 'climate-data-online',
    family: 'climate',
    label: 'NCEI Climate Data Online',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'required',
    geographicCoverage: 'global',
    temporalCoverage: 'historical through present',
    updateCadence: 'on demand and periodic archives',
    validTimeSemantics: 'station, dataset, and archive valid times',
    supportedFormats: ['json', 'csv'],
    unitsOrProjectionNotes: 'station climate summaries and normals',
    latencyOrCostNotes: 'free public access with token registration',
    recommendedUseCases: [
      'historical weather',
      'normals and anomalies',
      'station climate summaries',
    ],
  },
  {
    sourceId: 'ncei-storm-events',
    productId: 'storm-events-database',
    family: 'climate',
    label: 'NCEI Storm Events Database',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: '1950 through present',
    updateCadence: 'as events are entered and archived',
    validTimeSemantics: 'event occurrence and archive dates',
    supportedFormats: ['json', 'csv'],
    unitsOrProjectionNotes: 'event summaries and impact metadata',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'historical severe-weather events',
      'event counts and impacts',
      'post-event research',
    ],
  },
] satisfies Array<WeatherSourceCatalogInput>

export const weatherSourceCatalogSchema = z.array(
  weatherSourceCatalogEntrySchema,
)

export const weatherSourceCatalog = weatherSourceCatalogSchema.parse(
  weatherSourceCatalogInput,
)
