import { z } from 'zod'

import { authRequirementSchema } from './base'

export const coverageSchema = z.enum(['global', 'conus', 'regional', 'local'])
export const sourceStatusSchema = z.enum(['implemented', 'scaffolded'])
export const sourceOfficialitySchema = z.enum(['official', 'secondary'])

export const weatherSourceCatalogEntrySchema = z.object({
  sourceId: z.string(),
  productId: z.string(),
  family: z.string(),
  label: z.string(),
  officiality: sourceOfficialitySchema,
  status: sourceStatusSchema.default('implemented'),
  authRequirement: authRequirementSchema,
  geographicCoverage: coverageSchema,
  temporalCoverage: z.string(),
  updateCadence: z.string(),
  validTimeSemantics: z.string(),
  supportedFormats: z.array(z.string()),
  unitsOrProjectionNotes: z.string(),
  latencyOrCostNotes: z.string(),
  recommendedUseCases: z.array(z.string()),
})

export type WeatherSourceCatalogEntry = z.infer<
  typeof weatherSourceCatalogEntrySchema
>

export const weatherSourceCatalog = [
  {
    sourceId: 'us-census-geocoder',
    productId: 'address-normalization',
    family: 'location',
    label: 'U.S. Census Geocoder',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'current',
    updateCadence: 'on demand',
    validTimeSemantics: 'geographic normalization only',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'lat/lon WGS84 output',
    latencyOrCostNotes: 'free public API',
    recommendedUseCases: [
      'U.S. address-like place normalization',
      'reverse geocoding support',
    ],
  },
  {
    sourceId: 'geonames',
    productId: 'global-geocoder',
    family: 'location',
    label: 'GeoNames',
    officiality: 'secondary',
    status: 'scaffolded',
    authRequirement: 'optional',
    geographicCoverage: 'global',
    temporalCoverage: 'current',
    updateCadence: 'on demand',
    validTimeSemantics: 'geographic normalization only',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'lat/lon WGS84 output',
    latencyOrCostNotes: 'free tier with username',
    recommendedUseCases: ['global place fallback'],
  },
  {
    sourceId: 'nominatim',
    productId: 'fallback-geocoder',
    family: 'location',
    label: 'Nominatim',
    officiality: 'secondary',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'current',
    updateCadence: 'on demand',
    validTimeSemantics: 'geographic normalization only',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'low-volume only',
    latencyOrCostNotes: 'use sparingly',
    recommendedUseCases: ['low-volume fallback'],
  },
  {
    sourceId: 'weather-gov',
    productId: 'points-forecast-hourly-observations-alerts',
    family: 'official-forecast',
    label: 'NWS Weather.gov API',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'current through 7 days',
    updateCadence: 'minutes to hours depending on product',
    validTimeSemantics: 'official valid periods from NWS products',
    supportedFormats: ['json', 'geojson'],
    unitsOrProjectionNotes: 'native imperial from NWS, normalized on read',
    latencyOrCostNotes: 'free public API',
    recommendedUseCases: [
      'current conditions',
      'forecast',
      'alerts',
      'official weather answers',
    ],
  },
  {
    sourceId: 'aviationweather-gov',
    productId: 'metar-taf',
    family: 'aviation',
    label: 'Aviation Weather Center Data API',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: 'current through 30 hours',
    updateCadence: 'minutes',
    validTimeSemantics: 'observation or forecast valid times from product',
    supportedFormats: ['json', 'xml'],
    unitsOrProjectionNotes: 'aviation native units',
    latencyOrCostNotes: 'free public API',
    recommendedUseCases: ['METAR', 'TAF', 'flight-weather context'],
  },
  {
    sourceId: 'spc',
    productId: 'outlooks-watches-mcd',
    family: 'severe',
    label: 'Storm Prediction Center',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'hours to day 8 outlook windows',
    updateCadence: 'scheduled updates and event-driven',
    validTimeSemantics: 'product issue and expiration windows',
    supportedFormats: ['json', 'geojson', 'text'],
    unitsOrProjectionNotes: 'polygon and text products',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'severe-weather setup',
      'watch context',
      'mesoscale discussion context',
    ],
  },
  {
    sourceId: 'wpc',
    productId: 'qpf-ero',
    family: 'precipitation',
    label: 'Weather Prediction Center',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'hours to day 7',
    updateCadence: 'scheduled forecast cycles',
    validTimeSemantics: 'issue and forecast valid periods',
    supportedFormats: ['json', 'text', 'image'],
    unitsOrProjectionNotes: 'QPF inches, outlook categorical',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: [
      'rainfall context',
      'flood potential',
      'multi-day precipitation questions',
    ],
  },
  {
    sourceId: 'nwps',
    productId: 'stream-forecast-observations',
    family: 'hydrology',
    label: 'NWPS',
    officiality: 'official',
    status: 'implemented',
    authRequirement: 'none',
    geographicCoverage: 'regional',
    temporalCoverage: 'current through official river forecast horizons',
    updateCadence: 'minutes to hours',
    validTimeSemantics: 'gauge obs time and forecast valid time',
    supportedFormats: ['json'],
    unitsOrProjectionNotes: 'river stage and flow metadata',
    latencyOrCostNotes: 'free public data',
    recommendedUseCases: ['river forecast context', 'flood-category summaries'],
  },
  {
    sourceId: 'nexrad',
    productId: 'base-reflectivity-velocity',
    family: 'radar',
    label: 'NEXRAD',
    officiality: 'official',
    status: 'scaffolded',
    authRequirement: 'none',
    geographicCoverage: 'regional',
    temporalCoverage: 'near real time',
    updateCadence: 'minutes',
    validTimeSemantics: 'scan time',
    supportedFormats: ['ar2v', 'png', 'json'],
    unitsOrProjectionNotes: 'radar polar grids',
    latencyOrCostNotes: 'public access with decoder requirements',
    recommendedUseCases: ['storm structure', 'short-fuse analysis'],
  },
  {
    sourceId: 'goes',
    productId: 'visible-ir-water-vapor',
    family: 'satellite',
    label: 'GOES',
    officiality: 'official',
    status: 'scaffolded',
    authRequirement: 'none',
    geographicCoverage: 'regional',
    temporalCoverage: 'near real time',
    updateCadence: 'minutes',
    validTimeSemantics: 'scan time',
    supportedFormats: ['netcdf', 'png'],
    unitsOrProjectionNotes: 'projection varies by product',
    latencyOrCostNotes: 'public access with image processing requirements',
    recommendedUseCases: [
      'cloud evolution',
      'water vapor analysis',
      'satellite interpretation',
    ],
  },
  {
    sourceId: 'mrms',
    productId: 'reflectivity-qpe',
    family: 'radar-analysis',
    label: 'MRMS',
    officiality: 'official',
    status: 'scaffolded',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: 'near real time',
    updateCadence: 'minutes',
    validTimeSemantics: 'analysis valid time',
    supportedFormats: ['grib2', 'png'],
    unitsOrProjectionNotes: 'gridded analysis products',
    latencyOrCostNotes: 'public data with decode cost',
    recommendedUseCases: [
      'precipitation totals',
      'composite reflectivity',
      'flood context',
    ],
  },
  {
    sourceId: 'hrrr',
    productId: 'short-range-model',
    family: 'model',
    label: 'HRRR',
    officiality: 'official',
    status: 'scaffolded',
    authRequirement: 'none',
    geographicCoverage: 'conus',
    temporalCoverage: '0 to 48 hours',
    updateCadence: 'hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: [
      'storm timing',
      'ongoing convection',
      'short-range detail',
    ],
  },
  {
    sourceId: 'gfs',
    productId: 'global-forecast-system',
    family: 'model',
    label: 'GFS',
    officiality: 'official',
    status: 'scaffolded',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: '0 to 16 days',
    updateCadence: '6-hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: ['days 2-10 context', 'broad synoptic pattern'],
  },
  {
    sourceId: 'gefs',
    productId: 'global-ensemble-forecast-system',
    family: 'model',
    label: 'GEFS',
    officiality: 'official',
    status: 'scaffolded',
    authRequirement: 'none',
    geographicCoverage: 'global',
    temporalCoverage: '0 to 16 days',
    updateCadence: '6-hourly',
    validTimeSemantics: 'ensemble init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public grib access',
    recommendedUseCases: ['spread and confidence', 'medium-range comparison'],
  },
  {
    sourceId: 'ecmwf-open-data',
    productId: 'ifs-aifs-open',
    family: 'model',
    label: 'ECMWF Open Data',
    officiality: 'official',
    status: 'scaffolded',
    authRequirement: 'optional',
    geographicCoverage: 'global',
    temporalCoverage: '0 to 15 days',
    updateCadence: '6-hourly',
    validTimeSemantics: 'model init and forecast valid times',
    supportedFormats: ['grib2'],
    unitsOrProjectionNotes: 'native model grids',
    latencyOrCostNotes: 'public subset, optional richer access with PAT',
    recommendedUseCases: ['medium-range comparison', 'global pattern context'],
  },
] satisfies Array<WeatherSourceCatalogEntry>

export const weatherSourceCatalogSchema = z.array(
  weatherSourceCatalogEntrySchema,
)
