from __future__ import annotations

from .models import CatalogResponse, ProductCatalogEntry, SourceCatalogEntry


def build_catalog() -> CatalogResponse:
    return CatalogResponse(
        sources=[
            SourceCatalogEntry(
                sourceId="nws",
                name="NWS / weather.gov",
                official=True,
                authRequired=False,
                geographicCoverage="United States and territories",
                temporalCoverage="Current through day 7 forecast products",
                refreshCadence="Observations update every few minutes; forecasts and alerts as issued",
                validTimeSemantics="Official forecast valid periods and alert effective windows",
                supportedFormats=["GeoJSON", "JSON-LD"],
                unitsNotes="NWS observations are SI-native with mixed end-user display fields",
                projectionNotes="Point and zone products; no map projection requirement in this service",
                latencyNotes="Low latency public API",
                costNotes="Free public access",
                recommendedUseCases=[
                    "Official forecast baseline",
                    "Active alerts and warnings",
                    "Nearest-station observations",
                ],
            ),
            SourceCatalogEntry(
                sourceId="nexrad",
                name="NEXRAD",
                official=True,
                authRequired=False,
                geographicCoverage="United States",
                temporalCoverage="Near-real-time radar volumes",
                refreshCadence="Every radar scan",
                validTimeSemantics="Volume scan and frame valid times",
                supportedFormats=["Level II", "Level III"],
                unitsNotes="Radar moments and dual-pol fields",
                projectionNotes="Site-centric radar geometry",
                latencyNotes="Public access with larger payloads",
                costNotes="Free public access",
                recommendedUseCases=[
                    "Convective evolution",
                    "Velocity structure",
                    "Radar loop generation",
                ],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="goes",
                name="GOES",
                official=True,
                authRequired=False,
                geographicCoverage="Americas and adjacent oceans",
                temporalCoverage="Near-real-time satellite imagery",
                refreshCadence="Minutes",
                validTimeSemantics="Frame timestamps",
                supportedFormats=["NetCDF", "cloud-optimized imagery"],
                unitsNotes="Brightness temperature and derived cloud products",
                projectionNotes="Fixed-grid satellite projection",
                latencyNotes="Public access with moderate payload sizes",
                costNotes="Free public access",
                recommendedUseCases=[
                    "Infrared and water-vapor interpretation",
                    "Cloud-top evolution",
                    "Satellite loop generation",
                ],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="mrms",
                name="MRMS",
                official=True,
                authRequired=False,
                geographicCoverage="United States",
                temporalCoverage="Near-real-time mosaics",
                refreshCadence="Minutes",
                validTimeSemantics="Analysis and short-term accumulation periods",
                supportedFormats=["GRIB2", "raster derivatives"],
                unitsNotes="Reflectivity and quantitative precipitation products",
                projectionNotes="National gridded analysis",
                latencyNotes="Public access with larger payloads",
                costNotes="Free public access",
                recommendedUseCases=[
                    "Composite reflectivity context",
                    "Rainfall accumulation",
                    "Flood-relevant precipitation analysis",
                ],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="ncep-models",
                name="NCEP guidance family",
                official=True,
                authRequired=False,
                geographicCoverage="United States and global depending on model",
                temporalCoverage="Sub-hourly through medium range guidance",
                refreshCadence="Hourly to 12-hourly by model",
                validTimeSemantics="Model init time plus forecast valid time",
                supportedFormats=["GRIB2"],
                unitsNotes="Deterministic and ensemble guidance fields",
                projectionNotes="Model-native and subset grids",
                latencyNotes="Higher latency and larger payloads than text APIs",
                costNotes="Free public access",
                recommendedUseCases=[
                    "Short-range timing questions",
                    "Model comparison",
                    "Research artifact generation",
                ],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="ecmwf-open",
                name="ECMWF open data",
                official=False,
                authRequired=False,
                geographicCoverage="Global",
                temporalCoverage="Short- to medium-range guidance",
                refreshCadence="Operational cycle cadence",
                validTimeSemantics="Model init time plus forecast valid time",
                supportedFormats=["GRIB2"],
                unitsNotes="Open subset guidance and AI-assisted products",
                projectionNotes="Model-native grids",
                latencyNotes="Good fallback for medium-range context",
                costNotes="Free public access subset",
                recommendedUseCases=[
                    "Days 2-10 comparison",
                    "Synoptic pattern context",
                    "Research mode guidance spread",
                ],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="nwps",
                name="NWPS / National Water Prediction Service",
                official=True,
                authRequired=False,
                geographicCoverage="United States",
                temporalCoverage="Current and forecast river stages",
                refreshCadence="As issued by forecast centers",
                validTimeSemantics="Observed values and forecast valid periods",
                supportedFormats=["JSON", "XML", "text products"],
                unitsNotes="River stage and flow metrics by gauge",
                projectionNotes="Gauge-centric metadata",
                latencyNotes="Public access",
                costNotes="Free public access",
                recommendedUseCases=[
                    "Flood context",
                    "River forecast summaries",
                    "Hydrology research threads",
                ],
                implemented=False,
            ),
        ],
        products=[
            ProductCatalogEntry(
                productId="nws-points",
                sourceId="nws",
                name="Points metadata lookup",
                category="location-resolution",
                refreshCadence="On request",
                validTimeSemantics="Immediate lookup",
                supportedFormats=["GeoJSON"],
                notes="Used to resolve forecast and observation endpoints for a coordinate.",
            ),
            ProductCatalogEntry(
                productId="nws-forecast",
                sourceId="nws",
                name="7-day forecast",
                category="forecast",
                refreshCadence="As forecast updates are issued",
                validTimeSemantics="Named forecast periods",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
            ),
            ProductCatalogEntry(
                productId="nws-hourly-forecast",
                sourceId="nws",
                name="Hourly forecast",
                category="forecast",
                refreshCadence="As forecast updates are issued",
                validTimeSemantics="Hourly forecast periods",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
            ),
            ProductCatalogEntry(
                productId="nws-observation",
                sourceId="nws",
                name="Nearest-station latest observation",
                category="observation",
                refreshCadence="Every few minutes",
                validTimeSemantics="Observation timestamp",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
            ),
            ProductCatalogEntry(
                productId="nws-alerts",
                sourceId="nws",
                name="Active alerts by point",
                category="alerts",
                refreshCadence="As alerts are issued or updated",
                validTimeSemantics="Effective and end times",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
            ),
            ProductCatalogEntry(
                productId="artifact-meteogram",
                sourceId="ncep-models",
                name="Simple meteogram graphic",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG"],
                notes="Implemented as a lightweight server-generated chart path.",
            ),
            ProductCatalogEntry(
                productId="artifact-research-report",
                sourceId="nws",
                name="Research report artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["HTML"],
                notes="Implemented as a lightweight report export path.",
            ),
            ProductCatalogEntry(
                productId="nexrad-loop",
                sourceId="nexrad",
                name="Radar loop generation",
                category="radar",
                refreshCadence="Every radar scan",
                validTimeSemantics="Frame and loop times",
                supportedFormats=["PNG", "GIF", "MP4"],
                notes="Catalog stub for later extension.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="goes-loop",
                sourceId="goes",
                name="Satellite loop generation",
                category="satellite",
                refreshCadence="Minutes",
                validTimeSemantics="Frame and loop times",
                supportedFormats=["PNG", "GIF", "MP4"],
                notes="Catalog stub for later extension.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="hrrr-subset",
                sourceId="ncep-models",
                name="HRRR subset fetch",
                category="model-guidance",
                refreshCadence="Hourly",
                validTimeSemantics="Model init and valid times",
                supportedFormats=["GRIB2", "derived JSON"],
                notes="Catalog stub for later extension.",
                implemented=False,
            ),
        ],
    )
