from __future__ import annotations

from .models import CatalogResponse, ProductCatalogEntry, SourceCatalogEntry


def build_catalog() -> CatalogResponse:
    return CatalogResponse(
        sources=[
            SourceCatalogEntry(
                sourceId="nws",
                name="NWS / weather.gov",
                official=True,
                authRequired=False,
                geographicCoverage="United States and territories",
                temporalCoverage="Current through day 7 forecast products",
                refreshCadence="Minutes to hours",
                validTimeSemantics="Official forecast valid periods and alert windows",
                supportedFormats=["GeoJSON", "JSON-LD"],
                unitsNotes="SI-native observations with mixed display fields",
                projectionNotes="Point and zone products",
                latencyNotes="Low latency public API",
                costNotes="Free public access",
                recommendedUseCases=["Current weather", "Forecasts", "Alerts"],
                implemented=True,
            ),
            SourceCatalogEntry(
                sourceId="raincheck-artifacts",
                name="RainCheck artifact generator",
                official=False,
                authRequired=False,
                geographicCoverage="Request-scoped derived outputs",
                temporalCoverage="On-request generation from supplied weather inputs",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp and caller-provided valid windows",
                supportedFormats=["JSON", "HTML", "SVG"],
                unitsNotes="Derived charts, storyboards, and reports",
                projectionNotes=None,
                latencyNotes="Local generation after upstream weather data collection",
                costNotes="Free public access",
                recommendedUseCases=[
                    "Weather briefings",
                    "Radar and satellite storyboards",
                    "Hydrograph and sounding charts",
                ],
                implemented=True,
            ),
            SourceCatalogEntry(
                sourceId="aviationweather-gov",
                name="Aviation Weather Center",
                official=True,
                authRequired=False,
                geographicCoverage="Global",
                temporalCoverage="Current through short-range aviation products",
                refreshCadence="Minutes",
                validTimeSemantics="Product issue and valid windows",
                supportedFormats=["JSON", "XML", "text"],
                unitsNotes="Aviation-native units and station identifiers",
                projectionNotes=None,
                latencyNotes="Free public API",
                costNotes="Free public access",
                recommendedUseCases=["METAR", "TAF", "Aviation hazards"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="spc",
                name="Storm Prediction Center",
                official=True,
                authRequired=False,
                geographicCoverage="CONUS",
                temporalCoverage="Day 1 through Day 8 severe-weather windows",
                refreshCadence="Scheduled outlook cycles",
                validTimeSemantics="Issue times and outlook windows",
                supportedFormats=["HTML", "text"],
                unitsNotes="Narrative severe-weather context",
                projectionNotes=None,
                latencyNotes="Public page and product access",
                costNotes="Free public access",
                recommendedUseCases=["Severe weather", "Fire weather"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="wpc",
                name="Weather Prediction Center",
                official=True,
                authRequired=False,
                geographicCoverage="CONUS",
                temporalCoverage="Hours through day 7 guidance",
                refreshCadence="Scheduled forecast cycles",
                validTimeSemantics="Issue and forecast valid periods",
                supportedFormats=["HTML", "text", "image"],
                unitsNotes="QPF inches and categorical outlooks",
                projectionNotes=None,
                latencyNotes="Free public access",
                costNotes="Free public access",
                recommendedUseCases=["Rainfall", "Flood potential", "Winter weather"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="nwps",
                name="National Water Prediction Service",
                official=True,
                authRequired=False,
                geographicCoverage="United States",
                temporalCoverage="Current and forecast river stages",
                refreshCadence="As issued by forecast centers",
                validTimeSemantics="Observed values and forecast valid periods",
                supportedFormats=["JSON", "XML", "text"],
                unitsNotes="River stage and flow metrics by gauge",
                projectionNotes="Gauge-centric metadata",
                latencyNotes="Public access",
                costNotes="Free public access",
                recommendedUseCases=["Flood context", "River forecasts"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="nexrad",
                name="NEXRAD",
                official=True,
                authRequired=False,
                geographicCoverage="United States",
                temporalCoverage="Near-real-time radar volumes",
                refreshCadence="Every radar scan",
                validTimeSemantics="Volume scan and frame valid times",
                supportedFormats=["Level II", "Level III"],
                unitsNotes="Radar moments and dual-pol fields",
                projectionNotes="Site-centric radar geometry",
                latencyNotes="Public access with larger payloads",
                costNotes="Free public access",
                recommendedUseCases=["Radar loops", "Storm structure"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="goes",
                name="GOES-R / GOES ABI",
                official=True,
                authRequired=False,
                geographicCoverage="Americas and adjacent oceans",
                temporalCoverage="Near-real-time satellite imagery",
                refreshCadence="Minutes",
                validTimeSemantics="Frame timestamps",
                supportedFormats=["NetCDF", "cloud-optimized imagery"],
                unitsNotes="Brightness temperature and derived cloud products",
                projectionNotes="Fixed-grid satellite projection",
                latencyNotes="Public access with moderate payload sizes",
                costNotes="Free public access",
                recommendedUseCases=["Satellite loops", "Water vapor", "Fog"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="mrms",
                name="MRMS",
                official=True,
                authRequired=False,
                geographicCoverage="United States",
                temporalCoverage="Near-real-time mosaics",
                refreshCadence="Minutes",
                validTimeSemantics="Analysis and short-term accumulation periods",
                supportedFormats=["GRIB2", "raster derivatives"],
                unitsNotes="Reflectivity and quantitative precipitation products",
                projectionNotes="National gridded analysis",
                latencyNotes="Public access with larger payloads",
                costNotes="Free public access",
                recommendedUseCases=["QPE", "Rainfall", "Hail diagnostics"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="ncep-models",
                name="NCEP guidance family",
                official=True,
                authRequired=False,
                geographicCoverage="United States and global depending on model",
                temporalCoverage="Sub-hourly through medium range guidance",
                refreshCadence="Hourly to 12-hourly by model",
                validTimeSemantics="Model init time plus forecast valid time",
                supportedFormats=["GRIB2"],
                unitsNotes="Deterministic and ensemble guidance fields",
                projectionNotes="Model-native and subset grids",
                latencyNotes="Higher latency and larger payloads than text APIs",
                costNotes="Free public access",
                recommendedUseCases=["Short-range timing", "Model comparison"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="ecmwf-open-data",
                name="ECMWF Open Data",
                official=True,
                authRequired=False,
                geographicCoverage="Global",
                temporalCoverage="Short- to medium-range guidance",
                refreshCadence="Operational cycle cadence",
                validTimeSemantics="Model init time plus forecast valid time",
                supportedFormats=["GRIB2"],
                unitsNotes="Open subset guidance",
                projectionNotes="Model-native grids",
                latencyNotes="Good fallback for medium-range context",
                costNotes="Free public access subset",
                recommendedUseCases=["Days 2-10 comparison", "Synoptic context"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="nhc",
                name="National Hurricane Center",
                official=True,
                authRequired=False,
                geographicCoverage="Atlantic and eastern Pacific basins",
                temporalCoverage="Seasonal tropical outlooks and active advisories",
                refreshCadence="At least every six hours when active",
                validTimeSemantics="Issue time and advisory windows",
                supportedFormats=["HTML", "text"],
                unitsNotes="Advisory and cone products only",
                projectionNotes=None,
                latencyNotes="Free public access",
                costNotes="Free public access",
                recommendedUseCases=["Tropical outlooks", "Landfall risk"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="upper-air",
                name="Upper-air soundings",
                official=True,
                authRequired=False,
                geographicCoverage="United States and global archives",
                temporalCoverage="Current and recent observed soundings",
                refreshCadence="Multiple times per day",
                validTimeSemantics="Observation release time",
                supportedFormats=["text", "HTML", "JSON"],
                unitsNotes="Pressure-based vertical profiles",
                projectionNotes=None,
                latencyNotes="Public access",
                costNotes="Free public access",
                recommendedUseCases=["CAPE and shear", "Teaching", "Storm setup"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="ncei-climate",
                name="NCEI climate data",
                official=True,
                authRequired=True,
                geographicCoverage="United States and global archives",
                temporalCoverage="Historical through present climate records",
                refreshCadence="Daily to on-demand archive access",
                validTimeSemantics="Station date or climate period",
                supportedFormats=["JSON", "CSV", "text"],
                unitsNotes="Station and gridded climate summaries",
                projectionNotes=None,
                latencyNotes="Token-based public archive access",
                costNotes="Free public access with token",
                recommendedUseCases=["Normals", "Anomalies", "Station history"],
                implemented=False,
            ),
            SourceCatalogEntry(
                sourceId="storm-events",
                name="NCEI Storm Events Database",
                official=True,
                authRequired=False,
                geographicCoverage="United States",
                temporalCoverage="1950 through present public archive",
                refreshCadence="Updated as storm reports are curated",
                validTimeSemantics="Event start and end times",
                supportedFormats=["CSV", "HTML", "JSON"],
                unitsNotes="Narrative severe-weather event records",
                projectionNotes=None,
                latencyNotes="Public archive with historical latency",
                costNotes="Free public access",
                recommendedUseCases=["Historical severe weather", "Post-event research"],
                implemented=False,
            ),
        ],
        products=[
            ProductCatalogEntry(
                productId="nws-forecast",
                sourceId="nws",
                name="7-day forecast",
                category="forecast",
                refreshCadence="As forecast updates are issued",
                validTimeSemantics="Named forecast periods",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="nws-hourly-forecast",
                sourceId="nws",
                name="Hourly forecast",
                category="forecast",
                refreshCadence="As forecast updates are issued",
                validTimeSemantics="Hourly forecast periods",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="nws-observation",
                sourceId="nws",
                name="Nearest-station latest observation",
                category="observation",
                refreshCadence="Every few minutes",
                validTimeSemantics="Observation timestamp",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="nws-alerts",
                sourceId="nws",
                name="Active alerts by point",
                category="alerts",
                refreshCadence="As alerts are issued or updated",
                validTimeSemantics="Effective and end times",
                supportedFormats=["GeoJSON"],
                notes="Implemented in the Python service.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-meteogram",
                sourceId="raincheck-artifacts",
                name="Simple meteogram graphic",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG"],
                notes="Implemented as a lightweight chart path fed by caller-provided forecast points.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-research-report",
                sourceId="raincheck-artifacts",
                name="Research report artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["HTML"],
                notes="Implemented as a lightweight report export path.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-brief-report",
                sourceId="raincheck-artifacts",
                name="Brief weather report artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["HTML"],
                notes="Compact report export path for concise weather briefings.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-radar-loop",
                sourceId="raincheck-artifacts",
                name="Radar loop artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG", "HTML"],
                notes="Deterministic storyboard for radar frame sequences.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-satellite-loop",
                sourceId="raincheck-artifacts",
                name="Satellite loop artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG", "HTML"],
                notes="Deterministic storyboard for satellite frame sequences.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-hydrograph",
                sourceId="raincheck-artifacts",
                name="Hydrograph artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG"],
                notes="Deterministic river-stage style chart from structured series inputs.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-skewt",
                sourceId="raincheck-artifacts",
                name="Skew-T artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG"],
                notes="Deterministic sounding graphic from structured profile inputs.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-rainfall-chart",
                sourceId="raincheck-artifacts",
                name="Rainfall chart artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG"],
                notes="Deterministic precipitation chart from structured point or series inputs.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="artifact-snowfall-chart",
                sourceId="raincheck-artifacts",
                name="Snowfall chart artifact",
                category="artifact",
                refreshCadence="On request",
                validTimeSemantics="Request timestamp",
                supportedFormats=["SVG"],
                notes="Deterministic snowfall chart from structured point or series inputs.",
                implemented=True,
            ),
            ProductCatalogEntry(
                productId="spc-outlook",
                sourceId="spc",
                name="Severe-weather outlook and mesoscale context",
                category="severe",
                refreshCadence="Scheduled outlook cycles",
                validTimeSemantics="Issue time and outlook windows",
                supportedFormats=["HTML", "text"],
                notes="Catalog stub for severe-weather context products.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="spc-fire-weather",
                sourceId="spc",
                name="Fire-weather outlooks",
                category="severe",
                refreshCadence="Scheduled outlook cycles",
                validTimeSemantics="Issue time and outlook windows",
                supportedFormats=["HTML", "text"],
                notes="Catalog stub for wildfire spread-weather risk products.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="wpc-qpf-ero",
                sourceId="wpc",
                name="QPF and excessive rainfall outlook",
                category="precipitation",
                refreshCadence="Scheduled forecast cycles",
                validTimeSemantics="Issue and forecast valid periods",
                supportedFormats=["HTML", "text", "image"],
                notes="Catalog stub for rainfall and flash-flood context.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="wpc-winter-weather",
                sourceId="wpc",
                name="Winter weather probabilities",
                category="winter-weather",
                refreshCadence="Scheduled forecast cycles",
                validTimeSemantics="Issue and forecast valid periods",
                supportedFormats=["HTML", "text", "image"],
                notes="Catalog stub for snowfall and freezing-rain probabilities.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="wpc-medium-range-hazards",
                sourceId="wpc",
                name="Medium-range hazards",
                category="medium-range",
                refreshCadence="Scheduled forecast cycles",
                validTimeSemantics="Issue and forecast valid periods",
                supportedFormats=["HTML", "text", "image"],
                notes="Catalog stub for 3-7 day hazard summaries.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="nwps-river-forecast",
                sourceId="nwps",
                name="River gauge observations and forecasts",
                category="hydrology",
                refreshCadence="As issued by forecast centers",
                validTimeSemantics="Observed values and forecast valid periods",
                supportedFormats=["JSON", "XML", "text"],
                notes="Catalog stub for river-stage and flow products.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="nexrad-loop",
                sourceId="nexrad",
                name="Radar loop generation",
                category="radar",
                refreshCadence="Every radar scan",
                validTimeSemantics="Frame and loop times",
                supportedFormats=["PNG", "GIF", "MP4"],
                notes="Catalog stub for later extension.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="goes-loop",
                sourceId="goes",
                name="Satellite loop generation",
                category="satellite",
                refreshCadence="Minutes",
                validTimeSemantics="Frame and loop times",
                supportedFormats=["PNG", "GIF", "MP4"],
                notes="Catalog stub for later extension.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="mrms-analysis",
                sourceId="mrms",
                name="MRMS analysis products",
                category="radar-analysis",
                refreshCadence="Minutes",
                validTimeSemantics="Analysis valid time",
                supportedFormats=["GRIB2", "raster derivatives"],
                notes="Catalog stub for quantitative precipitation and hail/wind diagnostics.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="hrrr-subset",
                sourceId="ncep-models",
                name="HRRR subset fetch",
                category="model-guidance",
                refreshCadence="Hourly",
                validTimeSemantics="Model init and valid times",
                supportedFormats=["GRIB2", "derived JSON"],
                notes="Catalog stub for later extension.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="rap-subset",
                sourceId="ncep-models",
                name="RAP subset fetch",
                category="model-guidance",
                refreshCadence="Hourly",
                validTimeSemantics="Model init and valid times",
                supportedFormats=["GRIB2", "derived JSON"],
                notes="Catalog stub for short-range model guidance.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="nam-subset",
                sourceId="ncep-models",
                name="NAM subset fetch",
                category="model-guidance",
                refreshCadence="Hourly to 6-hourly",
                validTimeSemantics="Model init and valid times",
                supportedFormats=["GRIB2", "derived JSON"],
                notes="Catalog stub for mesoscale guidance.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="nbm-analysis",
                sourceId="ncep-models",
                name="National Blend of Models analysis",
                category="blend-analysis",
                refreshCadence="Hourly",
                validTimeSemantics="Analysis and forecast valid times",
                supportedFormats=["GRIB2", "derived JSON"],
                notes="Catalog stub for blended near-term guidance.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="gfs-global",
                sourceId="ncep-models",
                name="GFS global guidance",
                category="model-guidance",
                refreshCadence="6-hourly",
                validTimeSemantics="Model init and forecast valid times",
                supportedFormats=["GRIB2", "derived JSON"],
                notes="Catalog stub for global deterministic guidance.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="gefs-ensemble",
                sourceId="ncep-models",
                name="GEFS ensemble guidance",
                category="model-guidance",
                refreshCadence="6-hourly",
                validTimeSemantics="Ensemble init and forecast valid times",
                supportedFormats=["GRIB2", "derived JSON"],
                notes="Catalog stub for spread and confidence questions.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="ecmwf-open",
                sourceId="ecmwf-open-data",
                name="ECMWF Open Data guidance",
                category="model-guidance",
                refreshCadence="6-hourly",
                validTimeSemantics="Model init and forecast valid times",
                supportedFormats=["GRIB2"],
                notes="Catalog stub for medium-range comparison.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="nhc-outlook",
                sourceId="nhc",
                name="Tropical weather outlooks and advisories",
                category="tropical",
                refreshCadence="At least every six hours when active",
                validTimeSemantics="Issue time and advisory windows",
                supportedFormats=["HTML", "text"],
                notes="Catalog stub for basin and advisory products.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="upper-air-sounding",
                sourceId="upper-air",
                name="Observed sounding archive",
                category="upper-air",
                refreshCadence="Multiple times per day",
                validTimeSemantics="Observation release time",
                supportedFormats=["text", "HTML", "JSON"],
                notes="Catalog stub for current and recent sounding access.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="ncei-climate-summaries",
                sourceId="ncei-climate",
                name="Climate summaries and normals",
                category="historical-climate",
                refreshCadence="Daily to on-demand archive access",
                validTimeSemantics="Station date or climate period",
                supportedFormats=["JSON", "CSV", "text"],
                notes="Catalog stub for historical climate research.",
                implemented=False,
            ),
            ProductCatalogEntry(
                productId="storm-events-search",
                sourceId="storm-events",
                name="Storm Events search",
                category="historical-severe",
                refreshCadence="Updated as storm reports are curated",
                validTimeSemantics="Event start and end times",
                supportedFormats=["CSV", "HTML", "JSON"],
                notes="Catalog stub for historical severe-weather event lookup.",
                implemented=False,
            ),
        ],
    )
